# Generated by Django 4.2.8 on 2023-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_b64', models.TextField()),
                ('photo_b64', models.TextField(default=None, null=True)),
                ('linkedin_url', models.URLField(default=None, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('job_title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
