# Generated by Django 4.2.8 on 2023-12-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_user_card_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
    ]
