# Generated by Django 4.2.8 on 2023-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_linkedin_url_card_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='job_title',
            field=models.CharField(max_length=300),
        ),
    ]
