# Generated by Django 4.2.8 on 2023-12-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='qr_b64',
        ),
    ]
