# Generated by Django 4.2.8 on 2024-01-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_card_qr_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='region',
            field=models.CharField(default='Europe', max_length=20),
        ),
    ]
